# ============================================================================
#  Nón Lá Express — SiteGround WordPress deployment
#
#  Quick start
#    1. Fill in .live-sites/nonla.mk (copy from _template.mk). SiteGround shows
#       user/host/port under Site Tools → Devs → SSH Keys Manager.
#    2. make test-connection
#    3. make build-and-push
#
#  Everything under wordpress-theme/ is generated by
#  scripts/build-wordpress-theme.mjs. Never hand-edit it.
#
#  NOTE: `make build` runs the WordPress build (WP_BUILD=1), which is a
#  different output shape from `pnpm build` (prerendered, GitHub Pages).
#  Both ship from this one codebase — see svelte.config.js.
# ============================================================================

# Per-site credentials live in gitignored fragments so nothing sensitive is
# committed. Pass SITE=<key> to load .live-sites/<key>.mk.
SITE ?=

SITES_AVAILABLE := $(sort $(patsubst .live-sites/%.mk,%,$(filter-out .live-sites/_template.mk,$(wildcard .live-sites/*.mk))))

ifneq ($(SITE),)
  SITE_FILE := .live-sites/$(SITE).mk
  ifeq ($(wildcard $(SITE_FILE)),)
    $(error SITE=$(SITE) requested but $(SITE_FILE) does not exist. Copy .live-sites/_template.mk to $(SITE_FILE) and fill it in.)
  endif
  include $(SITE_FILE)
else ifeq ($(words $(SITES_AVAILABLE)),1)
  # Exactly one site configured: use it without needing SITE= on every command.
  # Credentials still live only in the gitignored fragment.
  SITE := $(SITES_AVAILABLE)
  include .live-sites/$(SITE).mk
endif

# ----- SSH connection (?= so a .live-sites fragment can override) -----
# One key pair is shared across every site in the same SiteGround account, so
# reuse ~/.ssh/siteground rather than generating a new one. A site under a
# different account gets its own key, named per account
# (e.g. ~/.ssh/siteground_jeffl208).
SITEGROUND_USER           ?= REPLACE_WITH_SSH_USER
SITEGROUND_DOMAIN         ?= REPLACE_WITH_DOMAIN.com
SITEGROUND_HOST           ?= ssh.$(SITEGROUND_DOMAIN)
SITEGROUND_PORT           ?= 18765
SITEGROUND_IDENTITY_FILE  ?= ~/.ssh/siteground

# ----- WordPress paths on the server -----
SITEGROUND_DOCROOT        ?= www/$(SITEGROUND_DOMAIN)/public_html
SITEGROUND_THEME_NAME     ?= nonla-express
SITEGROUND_REMOTE_PATH    ?= $(SITEGROUND_DOCROOT)/wp-content/themes/$(SITEGROUND_THEME_NAME)/

# ============================================================
#  Nothing below here should need editing
# ============================================================

LOCAL_THEME_DIR   := wordpress-theme
SITEGROUND_DIR    := ./siteground
LIVE_CONTENT_DIR  := .content-sync

RSYNC_OPTS      := -avz --delete --exclude='.DS_Store' --exclude='*.zip' --exclude='node_modules'
RSYNC_SSH_OPTS  := -e "ssh -p $(SITEGROUND_PORT) -i $(SITEGROUND_IDENTITY_FILE) -o IdentitiesOnly=yes"
RSYNC_HOST      := $(SITEGROUND_USER)@$(SITEGROUND_HOST)
SSH_OPTS        := -p $(SITEGROUND_PORT) -i $(SITEGROUND_IDENTITY_FILE) -o IdentitiesOnly=yes
WP              := cd $(SITEGROUND_DOCROOT) && wp

.PHONY: help info test-connection ssh connect build push build-and-push pull \
        purge-cache push-functions push-styles push-header \
        pull-content check-content-drift list-sites push-all build-and-push-all

.DEFAULT_GOAL := help

help:
	@echo "════════════════════════════════════════════════════════════════"
	@echo "  Nón Lá Express — WordPress deployment"
	@echo "════════════════════════════════════════════════════════════════"
	@echo ""
	@echo "Deploy:"
	@echo "  make build-and-push       Build the theme, rsync it up, purge caches"
	@echo "  make build                Build wordpress-theme/ locally only"
	@echo "  make push                 Rsync the existing wordpress-theme/ (no rebuild)"
	@echo "  make push-functions       Push functions.php alone (fast iteration)"
	@echo "  make push-styles          Push style.css alone"
	@echo "  make push-header          Push header.php + favicon"
	@echo "  make pull                 Download the live theme into ./siteground/"
	@echo "  make purge-cache          wp cache flush + wp sg purge"
	@echo ""
	@echo "Content sync (live WordPress is the source of truth for copy):"
	@echo "  make check-content-drift  Fail if the live site has edits this repo lacks"
	@echo "  make pull-content         Merge live edits into src/lib/content-overrides.json"
	@echo ""
	@echo "Connection:"
	@echo "  make info                 Show the resolved configuration"
	@echo "  make test-connection      Verify SSH works"
	@echo "  make ssh / connect        Interactive shell on the live server"
	@echo "  make list-sites           List configured .live-sites/ fragments"
	@echo "  make push-all             Push to every configured site"
	@echo "  make build-and-push-all   Build once, push to every configured site"
	@echo ""
	@echo "  Append SITE=<key> to target a site configured in .live-sites/<key>.mk."
	@echo ""

info:
	@echo "Site:          $(if $(SITE),$(SITE) (from .live-sites/$(SITE).mk),<Makefile defaults>)"
	@echo "Host:          $(SITEGROUND_HOST)"
	@echo "User:          $(SITEGROUND_USER)"
	@echo "Port:          $(SITEGROUND_PORT)"
	@echo "Identity file: $(SITEGROUND_IDENTITY_FILE)"
	@echo "Docroot:       $(SITEGROUND_DOCROOT)"
	@echo "Theme path:    $(SITEGROUND_REMOTE_PATH)"
	@echo "Local theme:   $(LOCAL_THEME_DIR)/"

test-connection:
	@echo "🔌 Testing SSH connection…"
	@ssh $(SSH_OPTS) $(RSYNC_HOST) "echo '✅ Connected.'; echo; uname -a; echo; wp --version || echo '⚠️  wp-cli not found on PATH'"

ssh connect:
	@ssh $(SSH_OPTS) $(RSYNC_HOST)

build:
	@pnpm run build:wordpress

push:
	@if [ ! -d "$(LOCAL_THEME_DIR)" ]; then \
		echo "❌ $(LOCAL_THEME_DIR)/ does not exist. Run: make build"; exit 1; \
	fi
	@echo "⬆️  Pushing $(LOCAL_THEME_DIR)/ → $(SITEGROUND_REMOTE_PATH)"
	@rsync $(RSYNC_OPTS) $(RSYNC_SSH_OPTS) --progress $(LOCAL_THEME_DIR)/ $(RSYNC_HOST):$(SITEGROUND_REMOTE_PATH)
	@echo "✅ Theme uploaded."

build-and-push: build push purge-cache
	@echo "🎉 Deployment complete."

pull:
	@mkdir -p $(SITEGROUND_DIR)
	@rsync -avz $(RSYNC_SSH_OPTS) --progress $(RSYNC_HOST):$(SITEGROUND_REMOTE_PATH) $(SITEGROUND_DIR)/
	@echo "✅ Live theme downloaded to $(SITEGROUND_DIR)/"

purge-cache:
	@echo "🧹 Purging caches…"
	@ssh $(SSH_OPTS) $(RSYNC_HOST) "$(WP) cache flush" || echo "⚠️  Could not flush the WP object cache — do it in Site Tools."
	@ssh $(SSH_OPTS) $(RSYNC_HOST) "$(WP) sg purge" || echo "⚠️  Could not purge SiteGround Dynamic Cache — do it in Site Tools."

push-functions:
	@rsync -avz $(RSYNC_SSH_OPTS) --progress $(LOCAL_THEME_DIR)/functions.php $(RSYNC_HOST):$(SITEGROUND_REMOTE_PATH)
	@$(MAKE) --no-print-directory purge-cache

push-styles:
	@rsync -avz $(RSYNC_SSH_OPTS) --progress $(LOCAL_THEME_DIR)/style.css $(RSYNC_HOST):$(SITEGROUND_REMOTE_PATH)

push-header:
	@rsync -avz $(RSYNC_SSH_OPTS) --progress $(LOCAL_THEME_DIR)/header.php $(LOCAL_THEME_DIR)/favicon.svg $(RSYNC_HOST):$(SITEGROUND_REMOTE_PATH)
	@$(MAKE) --no-print-directory purge-cache

# ------------------------------------------------------------------ content
# Live inline edits are stored in the WordPress database and SHADOW the copy in
# src/lib/content.js — a stale local default is invisible on the live site right
# up until someone resets content or greps the repo for copy that no longer
# matches production. These two targets close that trap.

$(LIVE_CONTENT_DIR)/.exported:
	@mkdir -p $(LIVE_CONTENT_DIR)
	@ssh $(SSH_OPTS) $(RSYNC_HOST) "$(WP) option list --search='xo_global_*' --format=json" \
	  > $(LIVE_CONTENT_DIR)/options.json
	@ssh $(SSH_OPTS) $(RSYNC_HOST) "$(WP) option get xo_route_overrides --format=json 2>/dev/null || echo '{}'" \
	  > $(LIVE_CONTENT_DIR)/route-overrides.json

pull-content:
	@echo "⬇️  Exporting live content from $(SITEGROUND_DOMAIN)…"
	@rm -f $(LIVE_CONTENT_DIR)/.exported
	@$(MAKE) --no-print-directory $(LIVE_CONTENT_DIR)/.exported
	@node scripts/merge-live-content.mjs
	@echo "   Review with: git diff src/lib/content-overrides.json"

check-content-drift:
	@rm -f $(LIVE_CONTENT_DIR)/.exported
	@$(MAKE) --no-print-directory $(LIVE_CONTENT_DIR)/.exported
	@node scripts/merge-live-content.mjs --check

list-sites:
	@echo "Configured sites in .live-sites/ ($(words $(SITES_AVAILABLE))):"
	@for s in $(SITES_AVAILABLE); do echo "  • $$s"; done
	@echo ""
	@echo "Usage: make build-and-push SITE=<key>"

# ------------------------------------------------------------------ fan-out
# One codebase, several installs. A failure on one site never stops the rest —
# the summary at the end lists whatever did fail.

push-all:
	@if [ -z "$(SITES_AVAILABLE)" ]; then echo "No .live-sites/*.mk configured."; exit 1; fi
	@echo "Push wordpress-theme/ to ALL $(words $(SITES_AVAILABLE)) sites:"
	@for s in $(SITES_AVAILABLE); do echo "    - $$s"; done
	@printf "Continue? [y/N] " && read ans && [ "$$ans" = "y" ] || { echo "Aborted."; exit 1; }
	@failed=""; \
	for s in $(SITES_AVAILABLE); do \
		echo ""; echo "═══ [$$s] ═══"; \
		if $(MAKE) --no-print-directory push SITE=$$s; then \
			$(MAKE) --no-print-directory purge-cache SITE=$$s || true; \
		else \
			echo "❌ push failed for $$s — continuing"; failed="$$failed $$s"; \
		fi; \
	done; \
	echo ""; \
	if [ -n "$$failed" ]; then echo "⚠️  Failures:$$failed"; exit 1; \
	else echo "🎉 Pushed to all $(words $(SITES_AVAILABLE)) sites."; fi

build-and-push-all: build
	@$(MAKE) --no-print-directory push-all
